### ISSUE TITLE
A problem occurred evaluating settings 'JzmanWanAndroid-master'.

### ISSUE THREAD

**Issue by YWzheng** [jzmanu/JzmanWanAndroid#1]
'JzmanWanAndroid/flutter_module/.android/include_flutter.groovy'
这是什么文件

**Comment by CodingForAndroid** [comment]
// Flutter Module add exist App
setBinding(new Binding([gradle: this]))
evaluate(new File(
        settingsDir.parentFile,
        'JzmanWanAndroid/flutter_module/.android/include_flutter.groovy'
))

老铁是不是少传东西了？

**Comment by sunqihui222** [comment]
我这也有
Could not find which method <init>() to invoke from this list:
  public javax.naming.Binding#<init>(java.lang.String, java.lang.String, java.lang.Object, boolean)
  public javax.naming.Binding#<init>(java.lang.String, java.lang.String, java.lang.Object)
  public javax.naming.Binding#<init>(java.lang.String, java.lang.Object, boolean)
  public javax.naming.Binding#<init>(java.lang.String, java.lang.Object)
Open File

能方便指点下么

**Comment by zj4074305** [comment]
仓库没有上传.android文件夹内容，从同名的flutter_moudle文件夹复制了一份

**Comment by jzmanu** [comment]
flutter_moudle要单独运行会自己生成所需文件，包括.android文件夹。

**Comment by mw666** [comment]
老铁请问具体怎么操作就解决这个问题

**Comment by sunqihui222** [comment]
可以给我个链接么，时间有点久了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jzmanu/JzmanWanAndroid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jzmanu/JzmanWanAndroid] A problem occurred evaluating settings 'JzmanWanAndroid-master'. (#1)





 
老铁请问具体怎么操作就解决这个问题

**Comment by mw666** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jzmanu/JzmanWanAndroid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 中午11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jzmanu/JzmanWanAndroid] A problem occurred evaluating settings 'JzmanWanAndroid-master'. (#1)

jzmanu/JzmanWanAndroid: Android原生+Flutter混合开发的WanAndroid开源客户端🔥 (github.com)


上面是链接请帮忙看一下

**Comment by sunqihui222** [comment]
jzmanu/JzmanWanAndroid: Android原生+Flutter混合开发的WanAndroid开源客户端🔥 (github.com) 



这个地址不全，我记得好像是掘金上的篇文章。我遇到的是在Android下找不到flutter 的相关内容，所以需要引入flutter moudle。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jzmanu/JzmanWanAndroid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 中午11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jzmanu/JzmanWanAndroid] A problem occurred evaluating settings 'JzmanWanAndroid-master'. (#1)





 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "jzmanu/JzmanWanAndroid"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年6月11日(星期五) 中午11:25 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [jzmanu/JzmanWanAndroid] A problem occurred evaluating settings 'JzmanWanAndroid-master'. (#1) 
 
 jzmanu/JzmanWanAndroid: Android原生+Flutter混合开发的WanAndroid开源客户端🔥 (github.com) 
 
 
 上面是链接请帮忙看一下

**Comment by mw666** [comment]
链接是

https://github.com/jzmanu/JzmanWanAndroid

项目弄下来报错：

Gradle sync failed: D:\wanAndroid\JzmanWanAndroid\flutter_module\.android\include_flutter.groovy (D:\wanAndroid\JzmanWanAndroid\flutter_module\.android\include_flutter.groovy)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jzmanu/JzmanWanAndroid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 中午11:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jzmanu/JzmanWanAndroid] A problem occurred evaluating settings 'JzmanWanAndroid-master'. (#1)





 jzmanu/JzmanWanAndroid: Android原生+Flutter混合开发的WanAndroid开源客户端🔥 (github.com)  
 
 
 
 这个地址不全，我记得好像是掘金上的篇文章。我遇到的是在Android下找不到flutter 的相关内容，所以需要引入flutter moudle。 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "jzmanu/JzmanWanAndroid"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年6月11日(星期五) 中午11:28 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [jzmanu/JzmanWanAndroid] A problem occurred evaluating settings 'JzmanWanAndroid-master'. (#1) 
 
 
 
 
 
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "jzmanu/JzmanWanAndroid"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年6月11日(星期五) 中午11:25  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [jzmanu/JzmanWanAndroid] A problem occurred evaluating settings 'JzmanWanAndroid-master'. (#1)  
   
  jzmanu/JzmanWanAndroid: Android原生+Flutter混合开发的WanAndroid开源客户端🔥 (github.com)  
   
   
  上面是链接请帮忙看一下

**Comment by mw666** [comment]
里面可能缺失了文件 请问这个怎么解决？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jzmanu/JzmanWanAndroid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 中午11:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jzmanu/JzmanWanAndroid] A problem occurred evaluating settings 'JzmanWanAndroid-master'. (#1)





 jzmanu/JzmanWanAndroid: Android原生+Flutter混合开发的WanAndroid开源客户端🔥 (github.com)  
 
 
 
 这个地址不全，我记得好像是掘金上的篇文章。我遇到的是在Android下找不到flutter 的相关内容，所以需要引入flutter moudle。 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "jzmanu/JzmanWanAndroid"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年6月11日(星期五) 中午11:28 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [jzmanu/JzmanWanAndroid] A problem occurred evaluating settings 'JzmanWanAndroid-master'. (#1) 
 
 
 
 
 
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "jzmanu/JzmanWanAndroid"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年6月11日(星期五) 中午11:25  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [jzmanu/JzmanWanAndroid] A problem occurred evaluating settings 'JzmanWanAndroid-master'. (#1)  
   
  jzmanu/JzmanWanAndroid: Android原生+Flutter混合开发的WanAndroid开源客户端🔥 (github.com)  
   
   
  上面是链接请帮忙看一下

**Comment by jzmanu** [comment]
> flutter_moudle要单独运行会自己生成所需文件，包括.android文件夹。

flutter_moudle要单独运行会自己生成所需文件，包括.android文件夹。
